# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a96d662d445a652fa606675fc10f318d17437ddae6bb1edf867dbc587b91b5534a64d6ef218e7cdc10d5a6c05b599ec57a9351ae37f82eabaae8ebcfa14d2384

test:
  secret_key_base: 9bafb8513b1f5b73a14bc1323bcaea5c5b640ae35909773873c0fc038fb9e4e6f539a00eec3f5033a07a7eede996c8d9146ff1bb105f53142369e15da80cbc03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
